package com.github.frankkwok.tij4.arrays;

import java.util.Arrays;

/**
 * Page 565
 * Exercise 3: Write a method that creates and initializes a twodimensional array of double. The size of the array is
 * determined by the arguments of the method, and the initialization values are a range determined by beginning and
 * ending values that are also arguments of the method. Create a second method that will print the array generated by
 * the first method. In main( ) test the methods by creating and printing several different sizes of arrays.
 * Exercise 4: Repeat the previous exercise for a three-dimensional array.
 * Exercise 5: Demonstrate that multidimensional arrays of nonprimitive types are automatically initialized to null.
 *
 * @author Frank Kwok on 2017/5/18.
 */
public class MultiDimArrayTest {
    public static void main(String[] args) {
        print(create(3, 5, 3, -1.0, 10.0));
        print(create(2, 2, 2, 0.0, 9.0));


        Object[][] objects = new Object[2][3];
        System.out.println(Arrays.deepToString(objects));
    }

    static double[][][] create(int l1, int l2, int l3, double from, double to) {
        double[][][] doubles = new double[l1][l2][l3];
        for (int i = 0; i < doubles.length; i++) {
            for (int j = 0; j < doubles[i].length; j++) {
                for (int k = 0; k < doubles[i][j].length; k++) {
                    doubles[i][j][k] = Math.random() * (to - from) + from;
                }
            }
        }
        return doubles;
    }

    private static void print(double[][][] doubles) {
        System.out.println(Arrays.deepToString(doubles));
    }
}
